version: "3.8"

services:
  app:
    image: overdosed22/all-time-high-backend:latest
    container_name: all-time-high-backend
    ports:
      - "9100:9100"
    env_file:
      - .env
    environment:
      LOG_FILE: /dev/stdout # 覆盖日志文件路径为标准输出
    volumes:
      - ./logs:/var/log/all-time-high-backend
    restart: always
