version: "3.8"

services:
  app:
    image: overdosed22/all-time-high-backend:latest
    container_name: all-time-high-backend
    ports:
      - "9100:9100"
    env_file:
      - .env
    environment:
      # 指定 LOG_FILE 环境变量到容器路径
      LOG_FILE: /var/log/all-time-high-backend/app.log
    volumes:
      # 挂载宿主机 logs 目录到容器
      - /home/ubuntu/all-time-high-test/logs:/var/log/all-time-high-backend
    restart: always
